name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  APP_NAME: helloworld
  DEPLOYMENTS_REPO: https://github.com/olehmart/test-deployments
  DEPLOYMENTS_DEV_BRANCH: auto-deployment-dev
  DEPLOYMENTS_DEV_CONFIG_PATH: dev/deployments.yaml
  DEPLOYMENTS_MAIN_BRANCH: main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Installs Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Makes prepare release script executable
      - run: chmod +x ./prepare-release.sh

      # Creates a new release
      - name: Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}

  triggerDeployment:
    name: Trigger Deployment
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Installs python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installs dependencies
      - name: Install Python dependencies
        working-directory: '.github/scripts/deployment_trigger'
        run: pip install -r requirements.txt

      # Triggers deployment
      - name: Trigger deployment
        working-directory: '.github/scripts/deployment_trigger'
        run: python main.py
        env:
          APP_NAME: ${{ env.APP_NAME }}
          NEW_VERSION: ${{ needs.release.outputs.new_release_version }}
          DEPLOYMENTS_REPO: ${{ env.DEPLOYMENTS_REPO }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOYMENTS_DEV_BRANCH: ${{ env.DEPLOYMENTS_DEV_BRANCH }}
          DEPLOYMENTS_DEV_CONFIG_PATH: ${{ env.DEPLOYMENTS_DEV_CONFIG_PATH }}
          DEPLOYMENTS_MAIN_BRANCH: ${{ env.DEPLOYMENTS_MAIN_BRANCH }}
