name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Installs Java
      - uses: actions/setup-java@v3
        with:
          distribution: 'microsoft'
          java-version: '17'

      # Makes prepare release script executable
      - run: chmod +x ./prepare-release.sh

      # Creates a new release
      - name: Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          extra_plugins: |
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
